- .github/PULL_REQUEST_TEMPLATE.md
pull request 작성 시 자동으로 양식이 생성됨
> Docs: pull request 양식 작성

- .github/workflows/gcp-ssh.yml
- .github/workflows/gradle.yml
- src/main/java/crush/myList/global/dto/JsonBody.java
- 현재 서버에서 DB 연결이 안되는 상황
- localhost 설정으로 DB 연결
> Fix: build 수정

- .github/workflows/gcp-ssh.yml
- .github/workflows/gradle.yml
- .gitignore
- build.gradle
- src/main/java/crush/myList/config/BeanConfig.java
- src/main/java/crush/myList/config/EnvBean.java
- src/main/java/crush/myList/domain/image/entity/Image.java
- src/main/java/crush/myList/domain/image/repository/ImageRepository.java
- src/main/java/crush/myList/domain/image/service/ImageService.java
- src/main/java/crush/myList/global/dto/JsonBody.java
- src/main/resources/application-gcs.yml
- src/main/resources/application.yml
- 이미지 관련 업로드 및 삭제 기능이 없었음.
- 플레이 리스트 API 구현 시 ImageService를 사용해서 gcs 이미지 처리가 가능함
추가된 파일
멀티파트파일을 사용해서 이미지 저장 (DB에도 저장됨)
이미지 삭제 (DB에도 삭제됨)
> GCS를 사용한 이미지 업로드 및 삭제 서비스 계층 구현

- src/main/java/crush/myList/config/SwaggerConfig.java
- src/main/java/crush/myList/domain/playlist/controller/PlaylistController.java
플레이리스트 API 경로가 "/api/v1"으로 시작하지 않음
플레이리스트 API 경로가 "api/v1"으로 시작. 스웨거 경로 config도 변경됨.
변경된 swagger config path
변경된 API 경로
> Refactor: Playlist API path

- src/main/java/crush/myList/config/EnvBean.java
- src/main/java/crush/myList/config/security/SecurityConfig.java
- src/main/resources/application-oauth2.yml
> Fix: 환경변수 누락

- src/main/java/crush/myList/config/EnvBean.java
- src/main/java/crush/myList/config/SwaggerConfig.java
- src/main/java/crush/myList/config/security/SecurityConfig.java
- src/main/java/crush/myList/domain/playlist/controller/PlaylistController.java
- src/main/resources/application-oauth2.yml
- 플레이 리스트 엔드포인트 수정
- 페이스북 로그인 환경변수 수정
> API 경로 수정, 환경변수 누락 수정

- .github/workflows/gcp-ssh.yml
- GCS_KEY_NAME 환경변수 누락
- GCS_KEY_NAME 환경변수 추가
> Fix: GCS_KEY_NAME 누락

- .github/workflows/gcp-ssh.yml
- LOGIN_PAGE 환경변수 .yml 등록 누락 수정
> Fix: LOGIN_PAGE 누락

- src/main/java/crush/myList/config/OAuth2/handler/LoginSuccessHandler.java
- src/main/java/crush/myList/domain/image/controller/ImageController.java
- src/main/java/crush/myList/domain/login/controller/LoginController.java
- src/main/java/crush/myList/domain/playlist/controller/PlaylistController.java
- src/main/java/crush/myList/exception/ErrorResponse.java
- src/main/java/crush/myList/global/dto/JsonBody.java
- src/main/java/crush/myList/global/dto/ResponseBody.java
- JsonBody의 status 타입 = HttpStatus
- JsonBody의 status 타입 = int
> Refactor: JsonBody status 타입 변경

- .github/workflows/gradle.yml
- .gitignore
- src/main/resources/application.yml
- TLS 인증서를 발급받아서 HTTPS로 동작합니다.
> Feat: HTTPS 긴급 적용

- .github/workflows/gradle.yml
- gradle.yml keystore 저장 경로 수정
> Fix: keystore 경로 수정

- .github/workflows/gcp-ssh.yml
- .github/workflows/gradle.yml
- gcp-ssh 의 build 과정에서 누락된 코드 추
> Fix: gcp-ssh.yml 수정

- src/main/java/crush/myList/config/OAuth2/handler/LoginFailureHandler.java
- src/main/java/crush/myList/config/security/SecurityConfig.java
- src/main/java/crush/myList/config/security/SecurityMember.java
- src/main/java/crush/myList/config/security/SecurityUserDetailsService.java
- src/main/java/crush/myList/domain/image/service/ImageService.java
- src/main/java/crush/myList/domain/member/controller/MemberController.java
- src/main/java/crush/myList/domain/member/dto/EditProfileReq.java
- src/main/java/crush/myList/domain/member/dto/EditProfileRes.java
- src/main/java/crush/myList/domain/member/dto/MemberDto.java
- src/main/java/crush/myList/domain/member/entity/Member.java
- src/main/java/crush/myList/domain/member/service/MemberService.java
- src/main/resources/application.yml
- SecurityMember 의 id 타입이 String
- SecurityMember 의 id 타입이 Long
- 사용자의 배경, 프로필 이미지, 닉네임 등 변경 API
SecurityMember 변경
사용자 프로필 수정 API
> Feat: 사용자 프로필 수정 API

- .github/workflows/gcp-ssh.yml
- .github/workflows/gradle.yml
- src/main/java/crush/myList/config/EnvBean.java
- src/main/java/crush/myList/config/OAuth2/handler/LoginSuccessHandler.java
- src/main/resources/application-oauth2.yml
- src/main/resources/application.yml
- jwt를 response body로 응답
- jwt를 query parm으로 응답
> Feat: 로그인 방식 변경

- src/main/java/crush/myList/config/OAuth2/handler/LoginSuccessHandler.java
> Fix: URI Encode 추가

- .github/workflows/deploy-develop.yml
- .github/workflows/deploy-main.yml
- 도커 이미지 해시 값 오류
- 도커 이미지 해시 값 수정
> Fix: 배포 과정에서 도커 이미지 해시값 오류 해결

- src/main/java/crush/myList/config/security/SecurityConfig.java
- security 경로 와일드카드
- security 경로 와일드카드 삭제
> Fix: security white list 문자열

- .github/workflows/deploy-develop.yml
> Fix: 테스트 서버 구글 리다이렉트 주소 수정

- src/main/java/crush/myList/config/OAuth2/handler/LoginSuccessHandler.java
> Refactor: 로그인 성공 시 리액트 주소 설정 변경

- .gitignore
- build.gradle
- src/main/java/crush/myList/domain/member/controller/MemberController.java
- src/test/java/crush/myList/controller/MemberControllerTest.java
- src/test/resources/application.yml
> Feat: 정보 수정 및 조회 API 테스트 코드

- src/main/java/crush/myList/config/OAuth2/OAuth2Service.java
- src/main/java/crush/myList/config/OAuth2/users/KakaoUser.java
- src/main/java/crush/myList/config/security/SecurityConfig.java
- src/main/java/crush/myList/domain/image/controller/ImageController.java
- src/main/java/crush/myList/domain/login/controller/LoginController.java
- src/main/resources/application-oauth2.yml
- 변경 전 jwt 발급 명세
- 변경 된 jwt 발급 명세 작성
- 카카오 로그인 구현 및 oauth2id 값 수정
로그인 API 명세 수정
카카오 로그인 지원
카카오 유저 클래스 구현
> API 명세 수정 및 카카오 로그인 구현

- src/main/java/crush/myList/config/OAuth2/handler/LoginSuccessHandler.java
- src/main/java/crush/myList/config/security/SecurityConfig.java
- src/main/java/crush/myList/domain/login/service/LoginService.java
- src/main/java/crush/myList/domain/member/service/MemberService.java
- src/main/java/crush/myList/exception/GlobalExceptionHandler.java
- src/main/resources/application.yml
- src/test/java/crush/myList/etc/LoginSuccessHandlerTest.java
- white list에 '/error' 미등록
- white list에 '/error' 등록
security white list에 /error 경로 추가
application.yml에 error 설정 추가
> Fix: 예외 처리 오류 수정 (security '/error' 경로 문제)

- src/main/java/crush/myList/config/setup/DummyData.java
- 사용자, 플레이 리스트 더미 데이터 자동 생성
더미 데이터 생성
config/setup/DummyData.java
> Feat: 사용자, 플레이 리스트 더미 데이터 추가

- src/main/java/crush/myList/config/security/SecurityConfig.java
- 모든 member api에 인증 필요
- 특정 사용자 조회, 닉네임 중복 검사 api 허용
spring security 에 api 경로 추가
> Feat: 사용자 api 권한 변동

- src/main/java/crush/myList/domain/music/Controller/MusicController.java
- src/main/java/crush/myList/domain/music/Service/MusicService.java
- src/main/java/crush/myList/domain/playlist/controller/PlaylistController.java
- src/main/java/crush/myList/domain/playlist/dto/PlaylistDto.java
- src/main/java/crush/myList/domain/playlist/service/PlaylistService.java
- src/main/java/crush/myList/exception/ErrorCode.java
- src/main/java/crush/myList/exception/ErrorResponse.java
- src/main/java/crush/myList/exception/GlobalExceptionHandler.java
- src/test/java/crush/myList/controller/MusicControllerTest.java
- src/test/java/crush/myList/controller/PlaylistControllerTest.java
Post API 경로 "/add"
API 오류코드 통일 되어 있음.
플레이리스트 수정 API가 PUT 메소드였음.
Post API 경로 수정 ("/add" -> "/"), 
API 오류코드 세분화 및 스웨거에 명시
플레이리스트 수정 API 메소드 변경(PUT -> PATCH)에 따른 로직 변경.
Post 경로 재변경
API 오류코드 세분화 및 스웨거 명시
> Api refactoring

- src/main/java/crush/myList/config/OAuth2/handler/LoginSuccessHandler.java
- src/main/java/crush/myList/domain/image/entity/Image.java
- src/main/resources/application.yml
- src/test/java/crush/myList/controller/MemberControllerTest.java
- access token 유효시간 10분
- access token 유효시간 100분으로 변경
> Feat: access token 유효시간 100분으로 설정

- .github/workflows/deploy-develop.yml
- .github/workflows/deploy-main.yml
- src/test/java/crush/myList/service/MemberServiceTest.java
- 카카오 환경변수 누락
- 카카오 환경변수 설정
환경변수 주입
> Fix: 카카오 로그인 환경변수 주입 오류

- .github/workflows/deploy-develop.yml
- 카카오, 페이스북 환경변수 누락
- 카카오, 페이스북 환경변수 설정
환경변수 주입
> Fix: 카카오, 페이스북 로그인 환경변수 주입 오류

- src/main/java/crush/myList/config/security/SecurityConfig.java
- src/main/java/crush/myList/domain/music/Controller/MusicController.java
- src/main/java/crush/myList/domain/playlist/controller/PlaylistController.java
- src/main/java/crush/myList/domain/playlist/dto/PlaylistDto.java
- src/main/java/crush/myList/domain/playlist/service/PlaylistService.java
- src/test/java/crush/myList/controller/MusicControllerTest.java
- src/test/java/crush/myList/controller/PlaylistControllerTest.java
음악 API 경로 "/playlist"로 시작함
플레이리스트 생성 API에 이름이 필수
플레이리스트 이미지 삭제 기능 추가
음악 API 경로 "/music"로 시작함 (시큐리티 화이트리스트도 변경)
플레이리스트 생성시 이름이 공백이면 "Untitled"로 생성
플레이리스트 이미지 삭제 기능 추가
음악 API 경로 변경
플레이리스트 생성 이름 입력을 선택사항으로 변경
> Feat: 플레이리스트 및 음악 기능 추가 및 변경

- src/main/java/crush/myList/config/OAuth2/OAuth2Service.java
- src/main/java/crush/myList/config/jwt/JwtTokenProvider.java
- src/main/java/crush/myList/config/security/SecurityConfig.java
- src/main/java/crush/myList/config/security/SecurityMember.java
- src/main/java/crush/myList/config/security/SecurityUserDetailsService.java
- src/main/java/crush/myList/config/setup/Authority.java
- src/main/java/crush/myList/config/setup/DummyData.java
- src/main/java/crush/myList/domain/member/controller/MemberController.java
- src/main/java/crush/myList/domain/member/entity/Member.java
- src/main/java/crush/myList/domain/member/entity/Role.java
- src/main/java/crush/myList/domain/member/enums/RoleName.java
- src/main/java/crush/myList/domain/member/repository/RoleRepository.java
- src/main/java/crush/myList/domain/member/service/MemberService.java
- src/main/java/crush/myList/domain/playlist/repository/PlaylistRepository.java
- src/test/java/crush/myList/controller/MemberControllerTest.java
- src/test/java/crush/myList/controller/MusicControllerTest.java
- src/test/java/crush/myList/controller/PlaylistControllerTest.java
- 사용자 닉네임 설정 유무를 매번 확인해야함.
- 사용자 역할 테이블 생성
- 사용자 닉네임 설정에 유무에 따라 역할 부여
- Member API 경로 변경
사용자 역할 테이블 생성
역할별 경로 설정
Member API 경로 변경
@wkdrhkdwls @yundevingV
> Member API 수정 및 사용자 역할 설정

- src/main/java/crush/myList/config/setup/DummyData.java
- src/main/java/crush/myList/domain/member/entity/Member.java
- src/main/java/crush/myList/domain/music/Repository/MusicRepository.java
- src/main/java/crush/myList/domain/playlist/controller/PlaylistController.java
- src/main/java/crush/myList/domain/playlist/service/PlaylistService.java
- src/test/java/crush/myList/controller/MemberControllerTest.java
- src/test/java/crush/myList/controller/PlaylistControllerTest.java
- 사용자의 역할 없을 수 있음
- 플레이리스트 단일 조회 api 추가
- 사용자의 역할 지정 필수로 변경
사용자 역할 필수 지정
플레이리스트 단일 조회 api 추가
@yundevingV
> Feat: 플레이리스트 단일 조회 API 추가

- src/main/java/crush/myList/config/security/SecurityConfig.java
- src/main/java/crush/myList/domain/autocomplete/controller/AutocompleteController.java
- src/main/java/crush/myList/domain/autocomplete/service/Autocomplete.java
- src/main/java/crush/myList/domain/autocomplete/service/GoogleAutocomplete.java
- src/test/java/crush/myList/service/GoogleAutocompleteTest.java
- ResponseStatusException 응답 이슈
- 자동완성 개수 제한이 없음
- ResponseStatusException 에러 처리 이슈 해결
- 자동완성 결과 최대 4개로 제한 
자동완성 인터페이스 수정
close #76    @DEMl4N  확인바람
> Feat: ResponseStatusException 에러 처리 이슈 해결 및 자동완성 결과 4개로 제한

- .github/workflows/build.yml
- .github/workflows/deploy-develop.yml
- .github/workflows/deploy-main.yml
- src/main/java/crush/myList/domain/member/entity/Member.java
- src/main/java/crush/myList/domain/music/Controller/MusicController.java
- src/main/java/crush/myList/domain/music/Repository/MusicRepository.java
- src/main/java/crush/myList/domain/music/Service/MusicService.java
- src/main/java/crush/myList/global/enums/LimitConstants.java
- src/test/java/crush/myList/controller/MemberControllerTest.java
- src/test/java/crush/myList/controller/MusicControllerTest.java
- 플레이 리스트 음악 조회 시 전부 조회
- 플레이 리스트 음악 조회 시 최대 6개씩 조회
플레이 리스트 음악 조회 시 페이징 적용
생성 시간 기준으로 내림차순 정렬
페이징 사이즈 6 고정
> Feat: 플레이 리스트 음악 조회 시 페이징 적용

- src/main/java/crush/myList/domain/music/Service/MusicService.java
- src/main/resources/application.yml
- ddl-auto update
- ddl-auto 수정 update -> create-drop
> Feat: ddl-auto 수정 update -> create-drop

- src/main/java/crush/myList/config/jwt/JwtAuthenticationFilter.java
> Feat: jwt 로그인 로그 추가

- src/main/java/crush/myList/config/jwt/JwtAuthenticationFilter.java
- src/main/java/crush/myList/config/jwt/JwtTokenProvider.java
- src/main/java/crush/myList/domain/music/Service/MusicService.java
- src/main/java/crush/myList/global/enums/LimitConstants.java
- src/test/java/crush/myList/controller/MusicControllerTest.java
- src/test/java/crush/myList/service/LoginServiceTest.java
- src/test/java/crush/myList/service/MemberServiceTest.java
- 음악 url을 검사하지 않음
- 음악 조회 페이징 크기 6
- 음악 url이 올바른 유튜브 url인지 정규식 검사
- 음악 조회 페이징 크기 9
유튜브 url 검사
페이징 크기 변경
close #88
> Feat: 음악 유튜브 url 정규식 검사

- src/main/java/crush/myList/domain/playlist/dto/PlaylistDto.java
- src/main/java/crush/myList/domain/playlist/service/PlaylistService.java
- src/test/java/crush/myList/controller/PlaylistControllerTest.java
플리 delete 메소드로 이미지 삭제
patch 메소드로 이미지 삭제 가능
플레이리스트 PATCH 삭제 여부 필드 추가
플레이리스트 PATCH 메소드에 이미지 삭제 여부 검사 로직 추가
위 기능 테스트 코드 작성
> 플레이리스트 PATCH 메소드 이미지 삭제 기능

- src/main/resources/application.yml
- ddl-auto create-drop
- ddl-auto create-drop -> update 변경
> Feat: ddl-auto create-drop -> update 변경

- src/main/java/crush/myList/config/setup/DummyData.java
- src/main/java/crush/myList/domain/playlist/repository/PlaylistRepository.java
- 더미 데이터 생성 과정에서 오류 발생
- 더미 데이터 생성 시 역할도 생성하여 오류 해결
역할 생성 코드를 더미 데이터 생성에도 추가함
> Refactor: 더미 데이터 생성 수정

- .github/workflows/build.yml
- .github/workflows/deploy-develop.yml
- .github/workflows/deploy-main.yml
- src/main/java/crush/myList/config/EnvBean.java
- src/main/java/crush/myList/config/OAuth2/handler/LoginFailureHandler.java
- src/main/java/crush/myList/config/OAuth2/handler/LoginSuccessHandler.java
- src/main/java/crush/myList/config/jwt/JwtTokenProvider.java
- src/main/java/crush/myList/config/security/SecurityConfig.java
- src/main/java/crush/myList/config/setup/DummyData.java
- src/main/java/crush/myList/domain/image/service/ImageService.java
- src/main/java/crush/myList/domain/login/controller/LoginController.java
- src/main/java/crush/myList/domain/login/dto/ReissueReq.java
- src/main/java/crush/myList/domain/login/service/LoginService.java
- src/main/java/crush/myList/domain/member/controller/MemberController.java
- src/main/java/crush/myList/domain/member/dto/EditProfileReq.java
- src/main/java/crush/myList/domain/member/service/UsernameService.java
- src/main/resources/application-oauth2.yml
- src/test/java/crush/myList/MyListApplicationTests.java
- src/test/java/crush/myList/controller/MemberControllerTest.java
- src/test/java/crush/myList/service/ImageServiceTest.java
- src/test/java/crush/myList/service/LoginServiceTest.java
- 환경변수 LOGIN_PAGE, REACT_URI 등 프론트 URI가 겹치는게 많음
- 프론트 URI는 REACT_URI로 통합
- 사용자 닉네임 pach api 제거
- 토큰 재발급 API 변경
- 이미지 서비스 단위 테스트 코드 추가
환경변수 삭제
사용자 닉네임 변경 API 삭제
토큰 재발급 API 수정
> 리팩토링 및 API 변경

- .github/workflows/build.yml
- .github/workflows/deploy-develop.yml
- .github/workflows/deploy-main.yml
- src/main/java/crush/myList/config/EnvBean.java
- src/main/java/crush/myList/domain/image/service/ImageService.java
- src/main/resources/application-gcs.yml
- src/main/resources/application.yml
- GCS에서 모든 이미지가 같은 경로에 저장됨
- ddl-auto = update
- GCS에서 이미지가 환경에 다른 경로에 저장되게 환경변수로 설정함
- mvp 배포를 위해서 ddl-auto를 none으로 바꿈
> Feat: GCS 버킷 이미지 저장 경로 분리, DDL-AUTO NONE 설정

- .github/workflows/build.yml
- .github/workflows/deploy-develop.yml
- .github/workflows/deploy-main.yml
- src/main/java/crush/myList/domain/image/service/ImageService.java
- src/main/resources/application.yml
- 토큰 발급시간 상수로 고정
- 토큰 발급시간 환경변수로 변경
- GCS 이미지 이슈 해결
> Feat: GCS 이미지 경로 이슈 해결 및 토큰 발급시간 환경변수로 변경

- src/main/java/crush/myList/domain/login/dto/ReissueReq.java
- src/main/java/crush/myList/domain/music/Controller/MusicController.java
- src/main/java/crush/myList/domain/music/Service/MusicService.java
- src/test/java/crush/myList/controller/MusicControllerTest.java
- src/test/java/crush/myList/controller/PlaylistControllerTest.java
음악 추가를 하나씩
리스트로 받아서 여러개 추가 가능
다중 음악 추가 기능
> Feat: 다중 음악 추가

- src/main/java/crush/myList/domain/music/Service/MusicService.java
- src/test/java/crush/myList/service/GoogleAutocompleteTest.java
- 음악 수정에만 url 검사
- 음악 등록에도 url 검사
> Fix: 음악 등록시 url 검사 로직 누락 수정

- src/main/java/crush/myList/domain/recommendation/controller/RecommendationController.java
- src/main/java/crush/myList/domain/recommendation/dto/RecommendationDto.java
- src/main/java/crush/myList/domain/recommendation/service/RandomRecommendationService.java
- src/main/java/crush/myList/domain/recommendation/service/Recommendation.java
- src/test/java/crush/myList/service/RandomRecommendationServiceTest.java
플레이리스트 추천 API Response에 소유자 유저네임 부재
DTO 추가 후 유저네임 추가
RecommendationDto 추가
> Recommendation Response에 유저네임 추가

- src/main/java/crush/myList/config/security/SecurityConfig.java
- src/main/java/crush/myList/config/security/SecurityMember.java
- src/main/java/crush/myList/domain/music/Repository/MusicRepository.java
- src/main/java/crush/myList/domain/playlist/controller/PlaylistController.java
- src/main/java/crush/myList/domain/playlist/dto/PlaylistDto.java
- src/main/java/crush/myList/domain/playlist/entity/Playlist.java
- src/main/java/crush/myList/domain/playlist/entity/PlaylistLike.java
- src/main/java/crush/myList/domain/playlist/repository/PlaylistLikeRepository.java
- src/main/java/crush/myList/domain/playlist/service/PlaylistService.java
- src/main/java/crush/myList/domain/recommendation/dto/RecommendationDto.java
- src/test/java/crush/myList/controller/PlaylistControllerTest.java
- src/test/java/crush/myList/controller/TestUtil.java
- src/test/java/crush/myList/service/RandomRecommendationServiceTest.java
- 플레이 리스트 좋아요 기능이 없음
- 플레이 리스트 단일 조회 시 좋아요 숫자와 좋아요 체크 여부를 알려줌
- 플레이 리스트 좋아요 및 취소 기능 
- Long 타입 컬럼 일부를 Integer로 변경
플레이 리스트 좋아요 엔티티
좋아요 숫자와 체크여부 확인
좋아요 하기 및 취소
플레이 리스트 응답 dto 수정
테스트 코드 추가
close #121
> Feat: playlist 좋아요 기능 추가

- src/main/java/crush/myList/config/security/SecurityConfig.java
- src/main/java/crush/myList/domain/playlist/controller/PlaylistController.java
- src/main/java/crush/myList/domain/playlist/dto/PlaylistLikeMember.java
- src/main/java/crush/myList/domain/playlist/repository/PlaylistLikeRepository.java
- src/main/java/crush/myList/domain/playlist/service/PlaylistService.java
- src/test/java/crush/myList/controller/PlaylistControllerTest.java
- 좋아요 누른 사용자 정보 조회 api 추가
좋아요 누른 사용자 정보 조회
테스트 코드
> Feat: playlist 좋아요 누른 사용자 조회

- src/main/java/crush/myList/domain/member/controller/MemberController.java
- src/main/java/crush/myList/domain/member/service/MemberService.java
- src/test/java/crush/myList/controller/MemberControllerTest.java
- src/test/java/crush/myList/controller/TestUtil.java
회원 탈퇴 기능 부재
회원 탈퇴 기능 추가
/member/me 에 delete 메소드로 추가
회원 탈퇴 시 프로필 이미지, 배경 이미지, 플레이리스트 이미지 등 모든 이미지를 GCS에서 삭제함
테스트 코드에서 영속성 전이가 되지 않아 임시적으로 수동으로 설정해주었음. 추후 수정 예정
Close #125
> Feat: 회원 탈퇴 기능 #125

- src/main/java/crush/myList/config/security/SecurityConfig.java
- src/main/java/crush/myList/domain/member/entity/Member.java
- src/main/java/crush/myList/domain/playlist/controller/PlaylistController.java
- src/main/java/crush/myList/domain/playlist/dto/GuestBookDto.java
- src/main/java/crush/myList/domain/playlist/dto/LikeMember.java
- src/main/java/crush/myList/domain/playlist/entity/GuestBook.java
- src/main/java/crush/myList/domain/playlist/entity/Playlist.java
- src/main/java/crush/myList/domain/playlist/repository/GuestBookRepository.java
- src/main/java/crush/myList/domain/playlist/service/GuestBookService.java
- src/main/java/crush/myList/domain/playlist/service/LikeService.java
- src/main/java/crush/myList/domain/playlist/service/PlaylistService.java
- src/main/java/crush/myList/domain/search/service/SearchService.java
- src/test/java/crush/myList/controller/PlaylistControllerTest.java
- src/test/java/crush/myList/controller/TestUtil.java
- 검색 API 사용 시 존재하는 사용자의 존재하는 이미지 조회에서 오류 발생
- SearchService 트랜잭션 누락 오류 수정
- 플레이리스트 방명록 추가
방명록
API
테스트 코드
close #126
> 플레이리스트 방명록 기능 및 오류 수정

- src/main/java/crush/myList/domain/playlist/service/LikeService.java
- 플레이리스트 좋아요 누른 사용자 조회 시 소개글 누락 
- 
- 플레이리스트 좋아요 누른 사용자 조회 시 소개글 추가
> Fix: 좋아요 누른 사용자 소개글 누락 수정

- src/main/java/crush/myList/config/setup/DummyData.java
- src/main/java/crush/myList/domain/search/dto/PlaylistDto.java
- src/main/java/crush/myList/domain/search/service/SearchService.java
- src/test/java/crush/myList/controller/SearchControllerTest.java
- name
- playlistName
플레이리스트 검색 결과
> refactor: search api 플레이리스트 결과 값 형식 수정

- src/main/java/crush/myList/domain/playlist/repository/PlaylistRepository.java
- src/main/java/crush/myList/domain/recommendation/service/RandomRecommendationService.java
- src/test/java/crush/myList/service/RandomRecommendationServiceTest.java
제목이 Untitled인 플레이리스트 추천
Untitled 제외
레포지토리 변경
> Feat unregistration

- src/main/java/crush/myList/domain/playlist/controller/PlaylistController.java
- src/main/java/crush/myList/domain/playlist/dto/GuestBookDto.java
- src/main/java/crush/myList/domain/playlist/service/GuestBookService.java
- src/main/java/crush/myList/domain/recommendation/dto/RecommendationDto.java
- src/main/java/crush/myList/domain/search/controller/SearchController.java
- src/main/java/crush/myList/domain/search/dto/PlaylistDto.java
- src/main/java/crush/myList/domain/search/dto/SearchDto.java
- src/main/java/crush/myList/domain/search/service/SearchService.java
- src/main/java/crush/myList/global/enums/LimitConstants.java
- src/test/java/crush/myList/controller/PlaylistControllerTest.java
- src/test/java/crush/myList/controller/TestUtil.java
- 플레이리스트 api 모두 같은 태그로 명세
- 플레이리스트 검색 결과 페이징 크기 6
- 플레이리스트 api 태그 분리
- 플레이리스트 검색 결과 페이징 크기 8
- 방명록 작성 요청 dto 수정
방명록 dto
검색 페이징 크기
플레이리스트 검색 결과에 유저네임 추가
> 프론트 요구사항 반영

- src/main/java/crush/myList/domain/playlist/controller/PlaylistController.java
- src/main/java/crush/myList/domain/playlist/repository/PlaylistLikeRepository.java
- src/main/java/crush/myList/domain/playlist/service/LikeService.java
- src/test/java/crush/myList/controller/PlaylistControllerTest.java
내가 좋아요한 플레이리스트 조회
컨트롤러 /playlist/like
LikeService 메소드 추가
> 131 todo 내가 좋아요 누른 플레이리스트 조회 #131

- src/main/java/crush/myList/domain/search/dto/PlaylistDto.java
- src/main/java/crush/myList/domain/search/service/SearchService.java
- src/test/java/crush/myList/controller/SearchControllerTest.java
플리 검색 결과에 음악 개수 없음
리스폰스에 음악 개수 추가
Response dto에 음악 개수 추가
close #140
> 140 todo 플레이리스트 검색결과 수정

- src/main/java/crush/myList/domain/playlist/dto/GuestBookDto.java
- src/main/java/crush/myList/domain/playlist/service/GuestBookService.java
- src/test/java/crush/myList/controller/PlaylistControllerTest.java
방명록 결과로 유저네임만 반환
방명록 조회, 작성, 수정 시 유저네임 뿐만 아니라 id, 프로필 사진도 반환
방명록 조회 스키마 예시
@wkdrhkdwls
Close #141
> 141 todo 방명록 조회 api 응답 수정 #141

- src/main/java/crush/myList/domain/recommendation/service/RandomRecommendationService.java
- src/main/java/crush/myList/global/enums/LimitConstants.java
- src/test/java/crush/myList/service/RandomRecommendationServiceTest.java
플리 추천 개수 4
6
플리 추천 개수 상수를 글로벌 enums로 리팩터
> Feat: 추천 플리 개수 4->6

- src/main/java/crush/myList/domain/member/controller/MemberController.java
- src/main/java/crush/myList/domain/member/entity/Member.java
- src/test/java/crush/myList/controller/MemberControllerTest.java
- src/test/java/crush/myList/controller/TestUtil.java
좋아요 시 회원탈퇴 불가능
멤버와 좋아요 엔티티 간 영속성 전이 설정하여 해결
> Fix: 좋아요 하면 회원탈퇴 불가능 버그 수정

- src/main/java/crush/myList/domain/recommendation/service/RandomRecommendationService.java
> Feat: 이미지 있는 플리만 추천

- src/main/java/crush/myList/domain/member/controller/MemberController.java
- src/main/java/crush/myList/domain/playlist/service/LikeService.java
유저 좋아요 플리 조회시 유저네임이 필수
유저네임이 없으면 액세스토큰으로 자신의 좋아요 플리 조회
> Feat: 유저네임 없이 자신의 좋아요 플리 조회 기능 추가

- src/main/java/crush/myList/config/OAuth2/users/CustomOAuth2User.java
- src/main/java/crush/myList/config/OAuth2/users/FaceBookUser.java
- src/main/java/crush/myList/config/OAuth2/users/GoogleUser.java
- src/main/java/crush/myList/config/OAuth2/users/KakaoUser.java
- src/main/java/crush/myList/domain/playlist/controller/PlaylistController.java
- src/main/java/crush/myList/domain/playlist/service/GuestBookService.java
- src/test/java/crush/myList/controller/PlaylistControllerTest.java
- src/test/java/crush/myList/controller/TestUtil.java
- src/test/java/crush/myList/service/GoogleAutocompleteTest.java
- 방명록의 작성자만 삭제 가능
- 플레이리스트 소유자는 타인의 방명록 삭제 가능
방명록 삭제 로직 변경
> Feat: 플레이리스트 소유자는 방명록을 자유롭게 삭제 가능

- src/main/java/crush/myList/config/security/SecurityConfig.java
- src/main/java/crush/myList/domain/festival/controller/FestivalController.java
- src/main/java/crush/myList/domain/festival/dto/FormData.java
- src/main/java/crush/myList/domain/festival/mongo/document/Form.java
- src/main/java/crush/myList/domain/festival/mongo/repository/FormRepository.java
- src/main/java/crush/myList/domain/festival/service/FestivalService.java
- src/main/java/crush/myList/exception/ErrorCode.java
- src/main/java/crush/myList/exception/GlobalExceptionHandler.java
- src/test/java/crush/myList/controller/FestivalControllerTest.java
- src/test/java/crush/myList/controller/TestUtil.java
- 축제 매칭 서비스 API 추가
- DB 에러 전역 핸들러 추가
form_data document
DB 무결성 위반 예외 핸들러
> Feat: 축제 폼 API 추가 및 DB 에러 전역 처리

- src/main/java/crush/myList/domain/festival/dto/FormData.java
- src/main/java/crush/myList/domain/member/dto/MemberDto.java
- src/main/java/crush/myList/domain/playlist/dto/GuestBookDto.java
- src/main/java/crush/myList/domain/playlist/service/GuestBookService.java
- src/main/java/crush/myList/domain/search/dto/MemberDto.java
- src/main/java/crush/myList/domain/search/dto/SearchDto.java
- 방명록 조회 시 수정 날짜만 yyyy-MM-dd 형식으로 제공
- 방명록 조회 시 생성 날짜도 제공. yyyy-MM-dd-HH:mm:ss 형식
> Feat: 방명록 조회 시 생성 시간 추가

- src/main/java/crush/myList/domain/playlist/dto/GuestBookDto.java
- src/main/java/crush/myList/domain/playlist/service/GuestBookService.java
> Feat: 방명록 응답 시간 포멧 수정

- src/main/java/crush/myList/domain/festival/dto/FormData.java
- src/main/java/crush/myList/domain/festival/mongo/document/Form.java
- src/test/java/crush/myList/controller/TestUtil.java
- form 클래스의 age 타입이 string
- form 클래스의 age 타입이 int
> Feat: 축제 매칭 신청 form age 자료형 변경

- src/main/java/crush/myList/config/security/SecurityConfig.java
- src/main/resources/application-oauth2.yml
> Chore: tls 재발급 경로 설정

- src/main/java/crush/myList/domain/member/dto/MemberDto.java
- src/main/java/crush/myList/domain/member/entity/Member.java
- src/main/java/crush/myList/domain/playlist/dto/PlaylistDto.java
- src/main/java/crush/myList/domain/playlist/entity/Playlist.java
- src/main/java/crush/myList/domain/playlist/service/PlaylistService.java
- src/main/java/crush/myList/domain/viewcounting/dto/ViewDto.java
- src/main/java/crush/myList/domain/viewcounting/entity/View.java
- src/main/java/crush/myList/domain/viewcounting/entity/ViewEntity.java
- src/main/java/crush/myList/domain/viewcounting/repository/ViewRepository.java
- src/main/java/crush/myList/domain/viewcounting/service/ViewService.java
- src/test/java/crush/myList/controller/PlaylistControllerTest.java
- src/test/java/crush/myList/controller/TestUtil.java
유저 및 플레이리스트 하루 / 전체 조회수 기능 추가
Close #113
> Feat: view count #113

- src/main/java/crush/myList/domain/member/dto/MemberDto.java
- src/main/java/crush/myList/domain/member/service/MemberService.java
- src/test/java/crush/myList/controller/MemberControllerTest.java
- src/test/java/crush/myList/controller/TestUtil.java
유저 조회수 기능 부재
특정 회원 정보 조회 api 요청시 조회수 증가 및 리스폰스 필드에 조회수 추가
> Feat: 유저 조회수 기능

- .github/workflows/deploy-main.yml
- src/main/java/crush/myList/config/OAuth2/OAuth2Service.java
- src/main/java/crush/myList/config/OAuth2/handler/LoginSuccessHandler.java
- src/main/java/crush/myList/config/security/SecurityConfig.java
- src/main/java/crush/myList/domain/music/mongo/document/Music.java
- src/main/java/crush/myList/domain/viewcounting/service/ViewService.java
- 멤버 엔티티에 뷰 엔티티가 없는 경우 NPE 발생
- NPE 발생 코드 수정
> 멤버 조회시 에러 발생 수정

- src/main/java/crush/myList/domain/member/service/MemberService.java
- src/main/java/crush/myList/domain/playlist/service/PlaylistService.java
- src/main/java/crush/myList/exception/GlobalExceptionHandler.java
- convertDto에서 NPE 오류 발생
- convertDto에서 NPE 수정
> Fix: 플레이리스트 조회시 NPE 오류 수정

- src/main/java/crush/myList/domain/festival/controller/FestivalController.java
- src/main/java/crush/myList/domain/festival/dto/FormData.java
- src/main/java/crush/myList/domain/festival/mongo/document/Form.java
- src/main/java/crush/myList/domain/festival/mongo/repository/FormRepository.java
- src/main/java/crush/myList/domain/festival/service/FestivalService.java
- src/main/java/crush/myList/domain/member/entity/Member.java
- src/test/java/crush/myList/controller/FestivalControllerTest.java
- src/test/java/crush/myList/controller/TestUtil.java
- 축제 신청 폼에서 나이와 장르를 입력함
- 마이리스트 주소를 입력해야함
- 이름, 성별, username, 전화번호만 입력함
> Feat: 축제 매칭 신청에서 나이, 장르 삭제

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/build.yml
- .github/workflows/deploy-develop.yml
- .github/workflows/deploy-main.yml
- build.gradle
- src/main/java/crush/myList/config/EnvBean.java
- src/main/java/crush/myList/config/OAuth2/handler/LoginSuccessHandler.java
- src/main/java/crush/myList/config/jwt/JwtAuthenticationFilter.java
- src/main/java/crush/myList/config/jwt/JwtTokenProvider.java
- src/main/java/crush/myList/config/security/AdminMember.java
- src/main/java/crush/myList/config/security/AdminUserDetailsService.java
- src/main/java/crush/myList/config/security/SecurityConfig.java
- src/main/java/crush/myList/config/security/SecurityMemberService.java
- src/main/java/crush/myList/config/setup/InitData.java
- src/main/java/crush/myList/domain/admin/controller/AdminController.java
- src/main/java/crush/myList/domain/admin/mongo/document/Admin.java
- src/main/java/crush/myList/domain/admin/mongo/repository/AdminRepository.java
- src/main/java/crush/myList/domain/login/service/LoginService.java
- src/main/resources/application.yml
- src/main/resources/templates/home.html
- src/main/resources/templates/login.html
사용자 이용 현황을 손쉽게 볼 수 있도록 SSR 방식의 관리자 페이지를 구축.
Thymeleaf를 사용해서 MVC 패턴으로 웹 페이지 구현. 현재는 관리자 로그인 페이지 까지 구현함.
- 관리자 페이지에 접속하기 위한 인증 구현
로그인 화면
> Feat: 관리자 페이지 추가

- .github/workflows/deploy-develop.yml
- .github/workflows/deploy-main.yml
CI/CD 과정에서 application.yml 설정하는 부분에 ssl 옵션이 누락됨
- ssl 옵션 설정 누락
누락된 부분
> Fix: ssl 옵션 누락

- src/main/java/crush/myList/config/security/SecurityConfig.java
관리자 페이지 로그인 후 페이지 고정
- 관리자 페이지 로그인 후 페이지 고정
> 관리자 페이지 로그인 후 페이지 고정

- src/main/java/crush/myList/domain/admin/service/AdminService.java
- src/test/java/crush/myList/controller/AdminControllerTest.java
admin 페이지 오류 수정 및 테스트 코드 추가
- @Transaction 누락 오류
- @Transaction 누락 오류 수정
- 테스트 코드 추가
> Fix: admin 페이지 오류 수정 및 테스트 코드 추가

- src/main/resources/templates/index.html
이미지로 인해서 속도가 느려지기 때문에 프로필 제외
- 이미지로 인해서 속도가 느려지기 때문에 프로필 제외
- 테이블 크기 표시
> Feat: admin 페이지 이미지 제외

- src/main/resources/templates/index.html
> Feat: 관리자 페이지 사용자 링크 추가

- src/main/resources/templates/index.html
form 정보로 입력받은 사용자의 링크도 추가
form 데이터 사용자 링크 추가
> Feat: admin 사용자 링크 추가

- src/main/resources/templates/index.html
> 관리자 페이지 폼데이터 정보 사옹자 링크 추가

- src/main/java/crush/myList/domain/login/controller/LoginController.java
- src/main/java/crush/myList/domain/music/Controller/MusicController.java
- src/main/java/crush/myList/domain/music/Dto/MusicDto.java
- src/main/java/crush/myList/domain/music/Service/MusicService.java
- src/main/java/crush/myList/domain/playlist/controller/PlaylistController.java
- src/main/java/crush/myList/domain/playlist/dto/PlaylistDto.java
- src/main/java/crush/myList/domain/playlist/entity/Playlist.java
- src/test/java/crush/myList/controller/MusicControllerTest.java
음악을 하나씩 등록, 수정,삭제하는 방식에서 여러 개 변경하는 방식으로 변경
- 음악은 한 개씩 변경함
- 음악을 여러 개 한번에 변경함
> Feat: 플레이리스트 수정 시 사용하는 음악 API 수정

- src/main/resources/application.yml
- 유튜브 API 머지 후 서버가 정상 작동하지 않음 
- application.yml에 SSL관련 설정이 주석처리 되어있는 것을 확인하고 주석 해제
```application.yml```
- Before
- After
> Fix: SSL 설정 원상복구 및 서버가 정상 작동하지 않는 이슈 해결
